DROP DATABASE IF EXISTS employee_db;

CREATE DATABASE employee_db;

USE employee_db;

CREATE TABLE IF NOT EXISTS department (
id INT PRIMARY KEY,
name VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS role (
id INT PRIMARY KEY,
title VARCHAR(30) NOT NULL,
salary DECIMAL(10,2) NULL,
department_id INTEGER
);

CREATE TABLE IF NOT EXISTS employee (
id INT PRIMARY KEY,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
role_id INTEGER,
manager_id INTEGER
);